dependencies:
    - uniswap/v3-periphery@1.3.0
    - uniswap/v3-core@1.0.0
    - smartcontractkit/chainlink-brownie-contracts@1.1.1
    - OpenZeppelin/openzeppelin-contracts@3.4.0
    - aave/protocol-v2@1.0.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
networks:
  default: mainnet-fork
  mainnet-fork:
    aave_pool_addresses_provider: '0xb53c1a33016b2dc2ff3653530bff1848a515c8c5'
    weth: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
    dai: '0x6b175474e89094c44da98b954eedeac495271d0f'
    link: '0x514910771af9ca656af840dff83e8264ecf986ca'
    dai_eth_price: '0x773616E4d11A78F511299002da57A0a94577F1f4'
    uni_v2_router: '0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D'
    uni_v3_router: '0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45'